### ISSUE TITLE
Ask me a question

### ISSUE THREAD

**Issue by fera765** [Seung3837/Typescript-ReactJS-WebRTC-1-N-SFU#2]
In a project where there would be more than 1 million people connected in broadcast style, the ClubHouse App would this system handle?

the system would be audio only

**Comment by millo-L** [comment]
If WebRTC was used, it is highly likely that they used SFU methods because Mesh(P2P) methods are overloaded on clients and MCU methods can degrade real-time performance. (Of course, if they only send and receive audio, they may have developed their own transmission method.)

Assuming they used WebRTC,
They may have configured and used SFU servers on their own, or configured using WebRTC-related open source libraries such as kurento and mediasoup.

When load-balancing the server, they may have used the pub, sub of redis to proceed with the connection between peers.

**Comment by fera765** [comment]
Very good, I really liked this webrtc + react project of yours

I am thinking of making an implementation in my application, and I found this structure very good.

**Comment by millo-L** [comment]
Thank you for the compliment. If necessary, you can use the project for your application.
